import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";


const inter =  Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "CashTrackr",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className}
      >
        <h1>CashTrackr</h1>
        {children}
      </body>
    </html>
  );
}
